{
 "title": "GitLab CI Pipelines Statuses",
 "description": "This leverages the Prometheus exporter I wrote to fetch information about GitLab CI pipelines statuses.\n\nhttps://github.com/mvisonneau/gitlab-ci-pipelines-exporter",
 "tags": [
  "gitlab",
  "ci"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "FAILED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(gitlab_ci_pipeline_last_run_status{status=\"failed\"} > 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Average Pipeline Run Frequency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 2, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(gitlab_ci_pipeline_time_since_last_run_seconds)"
    }
   ]
  },
  {
   "title": "Average Pipeline Duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(gitlab_ci_pipeline_last_run_duration_seconds)"
    }
   ]
  },
  {
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(gitlab_ci_pipeline_last_run_status{status=\"success\"} * 1 > 0) or (gitlab_ci_pipeline_last_run_status{status=\"running\"} * 2 > 0) or (gitlab_ci_pipeline_last_run_status{status=\"failed\"} * 3 > 0)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "FAILED",
   "type": "table",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(max(gitlab_ci_pipeline_time_since_last_run_seconds) by (project, ref) * min(gitlab_ci_pipeline_last_run_status{status=~\"failed\"}) by (project, ref)) > 0"
    },
    {
     "expr": "(max(gitlab_ci_pipeline_last_run_duration_seconds) by (project, ref) * min(gitlab_ci_pipeline_last_run_status{status=~\"failed\"}) by (project, ref)) > 0"
    },
    {
     "expr": "min(gitlab_ci_pipeline_last_run_status{status=~\"failed\"}) by (project, ref) > 0"
    }
   ]
  },
  {
   "title": "HEALTHY & RUNNING",
   "type": "table",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max(gitlab_ci_pipeline_time_since_last_run_seconds) by (project, ref) unless (min(gitlab_ci_pipeline_status{status!~\"success|running\"}) by (project, ref) > 0)"
    },
    {
     "expr": "max(gitlab_ci_pipeline_last_run_duration_seconds) by (project, ref) unless (min(gitlab_ci_pipeline_status{status!~\"success|running\"}) by (project, ref) > 0)"
    },
    {
     "expr": "min(gitlab_ci_pipeline_status{status=~\"success\"} * 1) by (project, ref) > 0 or min(gitlab_ci_pipeline_status{status=~\"running\"} * 2) by (project, ref) > 0"
    }
   ]
  }
 ]
}